// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SOEA.Infrastructure.Data.Context;

#nullable disable

namespace SOEA.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SOEABdContext))]
    [Migration("20260512194752_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SOEA.Domain.Entities.Asignatura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alternancia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alternancia");

                    b.Property<int>("BloquesSemanales")
                        .HasColumnType("integer")
                        .HasColumnName("bloques_semanales");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("ProgramaId")
                        .HasColumnType("uuid")
                        .HasColumnName("programa_id");

                    b.Property<bool>("RequiereLab")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_lab");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_asignaturas_codigo");

                    b.HasIndex("ProgramaId")
                        .HasDatabaseName("ix_asignaturas_programa_id");

                    b.ToTable("Asignaturas", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.BloqueTiempo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dia");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.HasKey("Id");

                    b.HasIndex("Dia")
                        .HasDatabaseName("ix_bloque_tiempo_dia");

                    b.ToTable("BloqueTiempos", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.Docente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("correo");

                    b.Property<string>("Disponibilidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("disponibilidad");

                    b.Property<decimal>("MaximoHorasSemanales")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("maximo_horas_semanales");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_docentes_correo");

                    b.ToTable("Docentes", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.Espacio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<string>("Edificio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("edificio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("Piso")
                        .HasColumnType("integer")
                        .HasColumnName("piso");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_espacios_tipo");

                    b.ToTable("Espacios", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alternancia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alternancia");

                    b.Property<int>("EstudiantesInscritos")
                        .HasColumnType("integer")
                        .HasColumnName("estudiantes_inscritos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("ProgramaId")
                        .HasColumnType("uuid")
                        .HasColumnName("programa_id");

                    b.Property<int>("Semestre")
                        .HasColumnType("integer")
                        .HasColumnName("semestre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("ix_grupo_nombre");

                    b.HasIndex("ProgramaId")
                        .HasDatabaseName("ix_grupo_programa_id");

                    b.HasIndex("Semestre")
                        .HasDatabaseName("ix_grupo_semestre");

                    b.ToTable("Grupos", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.Horario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("GeneradoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<decimal>("PuntajeFitness")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("soft_constraint_fitness_score");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("semestre");

                    b.Property<string>("SesioneIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sesion_ids");

                    b.Property<int>("ViolacionesRestriccionesDuras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("hard_constraint_violations");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_horario_estado");

                    b.HasIndex("GeneradoEn")
                        .HasDatabaseName("ix_horario_generated_at");

                    b.HasIndex("Semestre")
                        .HasDatabaseName("ix_horario_semestre");

                    b.ToTable("Horarios", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.Sesion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alternancia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alternancia");

                    b.Property<Guid>("AsignaturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("asignatura_id");

                    b.Property<Guid>("BloqueTiempoId")
                        .HasColumnType("uuid")
                        .HasColumnName("bloque_tiempo_id");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("docente_id");

                    b.Property<decimal>("DuracionHoras")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("duracion_horas");

                    b.Property<bool>("EsBloque")
                        .HasColumnType("boolean")
                        .HasColumnName("es_bloque");

                    b.Property<Guid?>("EspacioId")
                        .HasColumnType("uuid")
                        .HasColumnName("espacio_id");

                    b.Property<bool>("EstaDividida")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_dividida");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidad");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId")
                        .HasDatabaseName("ix_sesion_asignatura_id");

                    b.HasIndex("BloqueTiempoId")
                        .HasDatabaseName("ix_sesion_bloque_tiempo_id");

                    b.HasIndex("DocenteId")
                        .HasDatabaseName("ix_sesion_docente_id");

                    b.HasIndex("EspacioId")
                        .HasDatabaseName("ix_sesion_espacio_id");

                    b.HasIndex("DocenteId", "BloqueTiempoId")
                        .HasDatabaseName("ix_sesion_docente_bloque_conflicto");

                    b.HasIndex("EspacioId", "BloqueTiempoId")
                        .HasDatabaseName("ix_sesion_espacio_bloque_conflicto");

                    b.ToTable("Sesiones", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
