// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SOEA.Infrastructure.Data.Context;

#nullable disable

namespace SOEA.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SOEABdContext))]
    [Migration("20260709224009_Etapa6DesglosePorTipoSesion")]
    partial class Etapa6DesglosePorTipoSesion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DisponibilidadDocente", b =>
                {
                    b.Property<Guid>("BloqueTiempoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uuid");

                    b.HasKey("BloqueTiempoId", "DocenteId");

                    b.HasIndex("DocenteId");

                    b.ToTable("DisponibilidadDocente");
                });

            modelBuilder.Entity("SOEA.Domain.Entities.AsignacionSemanal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BloqueTiempoId")
                        .HasColumnType("uuid")
                        .HasColumnName("bloque_tiempo_id");

                    b.Property<Guid?>("EspacioId")
                        .HasColumnType("uuid")
                        .HasColumnName("espacio_id");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidad");

                    b.Property<string>("Semana")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("semana");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.HasKey("Id");

                    b.HasIndex("SesionId")
                        .HasDatabaseName("ix_asignacion_semanal_sesion_id");

                    b.HasIndex("SesionId", "Semana")
                        .IsUnique()
                        .HasDatabaseName("ux_asignacion_semanal_sesion_semana");

                    b.HasIndex("EspacioId", "Semana", "BloqueTiempoId")
                        .HasDatabaseName("ix_asignacion_semanal_espacio_conflicto");

                    b.ToTable("AsignacionesSemanales", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.Asignatura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alternancia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alternancia");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Obligatoria")
                        .HasColumnName("categoria");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<Guid?>("DocenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("docente_id");

                    b.Property<Guid?>("EspacioFijoId")
                        .HasColumnType("uuid")
                        .HasColumnName("espacio_fijo_id");

                    b.Property<TimeOnly?>("HoraFinMax")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fin_max");

                    b.Property<TimeOnly?>("HoraInicioMin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio_min");

                    b.Property<int>("HorasLaboratorio")
                        .HasColumnType("integer")
                        .HasColumnName("horas_laboratorio");

                    b.Property<int>("HorasTeoriaPresencial")
                        .HasColumnType("integer")
                        .HasColumnName("horas_teoria_presencial");

                    b.Property<int>("HorasTeoriaVirtual")
                        .HasColumnType("integer")
                        .HasColumnName("horas_teoria_virtual");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("ProgramaId")
                        .HasColumnType("uuid")
                        .HasColumnName("programa_id");

                    b.Property<int>("SesionesLaboratorioSemana")
                        .HasColumnType("integer")
                        .HasColumnName("sesiones_laboratorio_semana");

                    b.Property<int>("SesionesLaboratorioSemestre")
                        .HasColumnType("integer")
                        .HasColumnName("sesiones_laboratorio_semestre");

                    b.Property<int>("SesionesTeoriaPresencialSemana")
                        .HasColumnType("integer")
                        .HasColumnName("sesiones_teoria_presencial_semana");

                    b.Property<int>("SesionesTeoriaVirtualSemana")
                        .HasColumnType("integer")
                        .HasColumnName("sesiones_teoria_virtual_semana");

                    b.HasKey("Id");

                    b.HasIndex("ProgramaId")
                        .HasDatabaseName("ix_asignaturas_programa_id");

                    b.HasIndex("Codigo", "ProgramaId")
                        .IsUnique()
                        .HasDatabaseName("ix_asignaturas_codigo_programa");

                    b.ToTable("Asignaturas", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.BloqueTiempo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dia");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.HasKey("Id");

                    b.HasIndex("Dia")
                        .HasDatabaseName("ix_bloque_tiempo_dia");

                    b.ToTable("BloqueTiempos", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.Docente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("CedulaIdentidad")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cedula_identidad");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("correo");

                    b.Property<string>("Disponibilidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("disponibilidad");

                    b.Property<string>("DisponibilidadUiJson")
                        .HasColumnType("text")
                        .HasColumnName("disponibilidad_ui_json");

                    b.Property<decimal>("MaximoHorasSemanales")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("maximo_horas_semanales");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_docentes_correo");

                    b.ToTable("Docentes", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.Espacio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<string>("Edificio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("edificio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("Piso")
                        .HasColumnType("integer")
                        .HasColumnName("piso");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_espacios_tipo");

                    b.ToTable("Espacios", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.Facultad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("Facultades", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alternancia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alternancia");

                    b.Property<Guid?>("AsignaturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("asignatura_id");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Disponibilidad")
                        .HasColumnType("text")
                        .HasColumnName("disponibilidad");

                    b.Property<string>("DisponibilidadUiJson")
                        .HasColumnType("text")
                        .HasColumnName("disponibilidad_ui_json");

                    b.Property<int>("EstudiantesInscritos")
                        .HasColumnType("integer")
                        .HasColumnName("estudiantes_inscritos");

                    b.Property<Guid?>("FacultadId")
                        .HasColumnType("uuid")
                        .HasColumnName("facultad_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("ProgramaId")
                        .HasColumnType("uuid")
                        .HasColumnName("programa_id");

                    b.Property<int>("Semestre")
                        .HasColumnType("integer")
                        .HasColumnName("semestre");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId")
                        .HasDatabaseName("ix_grupo_asignatura_id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_grupo_codigo")
                        .HasFilter("codigo IS NOT NULL");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("ix_grupo_nombre");

                    b.HasIndex("ProgramaId")
                        .HasDatabaseName("ix_grupo_programa_id");

                    b.HasIndex("Semestre")
                        .HasDatabaseName("ix_grupo_semestre");

                    b.ToTable("Grupos", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.Horario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("GeneradoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<decimal>("PuntajeFitness")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("soft_constraint_fitness_score");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("semestre");

                    b.Property<string>("SesioneIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sesion_ids");

                    b.Property<int>("ViolacionesRestriccionesDuras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("hard_constraint_violations");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_horario_estado");

                    b.HasIndex("GeneradoEn")
                        .HasDatabaseName("ix_horario_generated_at");

                    b.HasIndex("Semestre")
                        .HasDatabaseName("ix_horario_semestre");

                    b.ToTable("Horarios", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.Programa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FacultadId")
                        .HasColumnType("uuid")
                        .HasColumnName("facultad_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("FacultadId")
                        .HasDatabaseName("ix_programas_facultad_id");

                    b.ToTable("Programas", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.Sesion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alternancia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alternancia");

                    b.Property<Guid>("AsignaturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("asignatura_id");

                    b.Property<Guid>("BloqueTiempoId")
                        .HasColumnType("uuid")
                        .HasColumnName("bloque_tiempo_id");

                    b.Property<bool>("Bloqueada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bloqueada");

                    b.Property<Guid?>("DocenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("docente_id");

                    b.Property<decimal>("DuracionHoras")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("duracion_horas");

                    b.Property<bool>("EsBloque")
                        .HasColumnType("boolean")
                        .HasColumnName("es_bloque");

                    b.Property<Guid?>("EspacioId")
                        .HasColumnType("uuid")
                        .HasColumnName("espacio_id");

                    b.Property<bool>("EstaDividida")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_dividida");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidad");

                    b.Property<string>("MotivoConflicto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PatronAlternanciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("patron_alternancia_id");

                    b.Property<string>("TipoFlujo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Laboratorio")
                        .HasColumnName("tipo_flujo");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId")
                        .HasDatabaseName("ix_sesion_asignatura_id");

                    b.HasIndex("BloqueTiempoId")
                        .HasDatabaseName("ix_sesion_bloque_tiempo_id");

                    b.HasIndex("DocenteId")
                        .HasDatabaseName("ix_sesion_docente_id");

                    b.HasIndex("EspacioId")
                        .HasDatabaseName("ix_sesion_espacio_id");

                    b.HasIndex("PatronAlternanciaId")
                        .HasDatabaseName("ix_sesion_patron_alternancia_id");

                    b.HasIndex("DocenteId", "BloqueTiempoId")
                        .HasDatabaseName("ix_sesion_docente_bloque_conflicto");

                    b.HasIndex("EspacioId", "BloqueTiempoId")
                        .HasDatabaseName("ix_sesion_espacio_bloque_conflicto");

                    b.ToTable("Sesiones", (string)null);
                });

            modelBuilder.Entity("SOEA.Domain.Entities.TipoAlternanciaConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("boolean")
                        .HasColumnName("es_sistema");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PatronBase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("patron_base");

                    b.Property<int>("SemanasPresenciales")
                        .HasColumnType("integer")
                        .HasColumnName("semanas_presenciales");

                    b.HasKey("Id");

                    b.ToTable("TiposAlternancia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Activo = true,
                            Color = "#1565c0",
                            EsSistema = true,
                            Nombre = "Tipo A",
                            PatronBase = "PresencialEnSemanaA",
                            SemanasPresenciales = 8
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Activo = true,
                            Color = "#e65100",
                            EsSistema = true,
                            Nombre = "Tipo B",
                            PatronBase = "PresencialEnSemanaB",
                            SemanasPresenciales = 8
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Activo = true,
                            Color = "#607d8b",
                            EsSistema = true,
                            Nombre = "Sin alternancia",
                            PatronBase = "SinAlternancia",
                            SemanasPresenciales = 16
                        });
                });

            modelBuilder.Entity("DisponibilidadDocente", b =>
                {
                    b.HasOne("SOEA.Domain.Entities.BloqueTiempo", null)
                        .WithMany()
                        .HasForeignKey("BloqueTiempoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SOEA.Domain.Entities.Docente", null)
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SOEA.Domain.Entities.Sesion", b =>
                {
                    b.HasOne("SOEA.Domain.Entities.TipoAlternanciaConfig", null)
                        .WithMany()
                        .HasForeignKey("PatronAlternanciaId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
